version: "3.1"

services:
  wishlist:
    build:
       context: ./wishlist
       dockerfile: Dockerfile-dev
    image: wishlist
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    
networks:
  front-tier:
  back-tier: