version: "3.1"

services:
  wishlistdb:
    image: mongo:latest
    volumes:
    - wishlist_data:/data/db
    ports:
      - "27017:27017" 
    networks:
      - back-tier
    

  wishlist:
    build:
       context: ./wishlist
       dockerfile: Dockerfile-dev
    image: wishlist
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - wishlistdb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://wishlistdb:27017/wishlistdb
    
networks:
  front-tier:
  back-tier:

volumes:
  wishlist_data:
    external: true