apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.namespace }}-{{ .Values.tag }}"
  name: backend
  labels:
{{ include "swaglist.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backendService.port }}
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-backend"
    app.kubernetes.io/instance: "{{ .Release.Name }}-backend"
