apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Values.namespace }}-{{ .Values.tag }}"
  name: file-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "nfs-client"
