FROM node:latest
WORKDIR /usr/src/wishlist/react-ui
COPY react-ui .
RUN npm install
RUN npm run build

FROM maven:latest
WORKDIR /usr/src/wishlist
COPY . .
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests

FROM java:8-jdk-alpine
WORKDIR /static
COPY --from=0 /usr/src/wishlist/react-ui/build/ .
WORKDIR /wishlist
COPY --from=1 /usr/src/wishlist/wishlist.application/target/wishlist.application-0.0.1-SNAPSHOT.jar .
EXPOSE 5005
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005","-jar", "/wishlist/wishlist.application-0.0.1-SNAPSHOT.jar"]
CMD ["--spring.profiles.active=dev"]
